name: iOS Build
run-name: ${{ github.event.inputs.build_name }}

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: Build Name
        required: true
        default: iOS Build
      clean_ios:
        description: Use Lime Clean iOS?
        type: boolean
        required: true
        default: true

jobs:
  buildiOS:
    runs-on: macos-latest

    env:
      HAXELIB_RUN: hl

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install HashLink
        run: brew install hashlink

      - name: Setup environment
        run: |
          brew install lua
          haxelib setup ~/haxelib
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Fix Lime
        run: |
          rm -rf ~/haxelib/lime
          rm -rf ~/.haxelib/lime
          haxelib install lime 8.1.2 --quiet
          export HXCPP_M64=1
          export HXCPP_ARM64=1
          haxelib run lime rebuild macos -hl -clean -verbose --skip-dependencies
          file ~/haxelib/lime/*/ndll/Mac64/lime.ndll

      - name: Setup iOS
        run: echo "n" | haxelib run lime setup ios -hl

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Rebuild LuaJIT
        run: haxelib run lime rebuild linc_luajit ios -hl -clean -verbose --skip-dependencies

      - name: Clean iOS
        if: ${{ github.event.inputs.clean_ios == 'true' }}
        run: haxelib run lime clean ios -hl

      - name: Haxelib List
        run: haxelib list

      - name: Build iOS
        run: |
          echo "${{ github.run_id }}" > VERSION
          haxelib run lime build ios -hl -D officialBuild -D LUA_ALLOWED

      - name: Archive iOS
        run: |
          xcodebuild \
            -workspace export/ios/build/PsychEngine.xcworkspace \
            -scheme PsychEngine \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/PsychEngine.xcarchive \
            archive

      - name: Export IPA
        run: |
          mkdir -p outputs/ipa/debug
          xcodebuild -exportArchive \
            -archivePath $PWD/build/PsychEngine.xcarchive \
            -exportPath $PWD/build/ipa \
            -exportOptionsPlist exportOptions.plist
          mv build/ipa/*.ipa outputs/ipa/debug/PsychEngine-debug.ipa || true

      - name: Find IPA
        run: find . -name "*.ipa"

      - uses: actions/upload-artifact@v4
        with:
          name: iosBuild
          path: outputs/ipa/debug/PsychEngine-debug.ipa
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        with:
          name: iosApp
          path: export/ios/build/Release-iphoneos/PsychEngine.app
