name: iOS Simulator Build
run-name: ${{ github.event.inputs.build_name }}

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: Build Name?
        required: true
        default: iOS Simulator Build
      clean_ios:
        description: Use Lime Clean iOS?
        type: boolean
        required: true
        default: true

jobs:
  buildiOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
          architecture: arm64

      - name: Setup environment
        run: |
          brew install lua
          haxelib setup ~/haxelib

      - name: Run setup script
        run: |
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Setup iOS
        run: echo "n" | haxelib run lime setup ios

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
     
      - name: Rebuild LuaJIT
        run: haxelib run lime rebuild linc_luajit ios -simulator -clean -verbose --skip-dependencies

      - name: Clean iOS
        if: ${{ github.event.inputs.clean_ios == 'true' }}
        run: haxelib run lime clean ios

      - name: Build iOS (Lime)
        run: |
          echo "${{ github.run_id }}" > VERSION
          haxelib run lime build ios -D officialBuild -D LUA_ALLOWED -nosign -simulator || true
           
      - name: Compile Xcode Project
        run: |
          xcodebuild \
           -project export/release/ios/PsychEngine.xcodeproj \
           -scheme PsychEngine \
           -configuration Release \
           -sdk iphonesimulator \
           -derivedDataPath $PWD/build \
           CODE_SIGNING_ALLOWED=NO \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGN_IDENTITY="" \
           build

      - name: Package for Appetize
        run: |
          cd build/Build/Products/Release-iphonesimulator/
          zip -qr PsychEngine-Simulator.zip PsychEngine.app

      - uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-zip
          path: build/Build/Products/Release-iphonesimulator/PsychEngine-Simulator.zip
          if-no-files-found: error
