name: Mobile Build
run-name: ${{ github.event.inputs.build_name }}

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: Build Name
        required: true
        default: Mobile Build
      clean:
        description: Use Lime Clean?
        type: boolean
        required: true
        default: true

jobs:
  buildAndroid:
    runs-on: macos-latest

    strategy:
     matrix:
      include:
        - platform: ios
          args: "-nosign -D officialBuild -D LUA_ALLOWED"
        - platform: android
          args: "-debug -D officialBuild -D LUA_ALLOWED"
   
    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Sudo
        if: matrix.platform == 'android'
        run: |
         sudo apt-get update
         sudo apt-get install -y build-essential clang openjdk-17-jdk wget unzip
          
      - name: Setup environment
        run: |
          haxelib setup ~/haxelib

          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Install Android SDK + NDK
        if: matrix.platform == 'android'
        run: |
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip

          mkdir cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Setup android lime
        if: matrix.platform == 'android'
        run: |
          printf "%s\n%s\n%s\n" \
            "$ANDROID_HOME" \
            "$ANDROID_NDK_ROOT" \
            "$JAVA_HOME" \
            | haxelib run lime setup android      

      - name: Setup ios lime
        if: matrix.platform == 'ios'
        run: echo "n" | haxelib run lime setup ios

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Force rebuild native libs
        run: haxelib run lime rebuild linc_luajit ${{ matrix.platform }} -clean

      - name: Clean ${{ matrix.platform }}
        if: ${{ github.event.inputs.clean == 'true' }}
        run: |
         haxelib run lime clean ${{ matrix.platform }}
    
      - name: Build
        run: |
         echo "${{ github.run_id }}" > VERSION
         haxelib run lime build ${{ matrix.platform }} ${{ matrix.args }}

      - name: Compile Xcode Project
        if: matrix.platform == 'ios'
        run: |
          xcodebuild \
           -project export/release/ios/PsychEngine.xcodeproj \
           -scheme PsychEngine \
           -configuration Release \
           -sdk iphoneos \
           -derivedDataPath $PWD/build \
           CODE_SIGNING_ALLOWED=NO \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGN_IDENTITY="" \
           build

      - name: Export Ipa
        if: matrix.platform == 'ios'
        run: |
          mkdir -p Payload
          
          cp -r $PWD/build/Build/Products/Release-iphoneos/PsychEngine.app Payload/
          
          mkdir -p outputs/ipa/debug
          zip -qr outputs/ipa/debug/PsychEngine-debug.ipa Payload
      
      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'android'
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug/PsychEngine-debug.apk
          
      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'ios'
        with:
          name: iosApp
          path: export/ios/build/Release-iphoneos/PsychEngine.app
