name: Mobile Build
run-name: ${{ github.event.inputs.build_name }}

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: Build Name
        required: true
        default: Mobile Build
      clean:
        description: Use Lime Clean?
        type: boolean
        required: true
        default: true

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang openjdk-17-jdk wget unzip

          haxelib setup ~/haxelib

          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Install Android SDK + NDK
        run: |
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip

          mkdir cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Setup lime
        run: |
          printf "%s\n%s\n%s\n" \
            "$ANDROID_HOME" \
            "$ANDROID_NDK_ROOT" \
            "$JAVA_HOME" \
            | haxelib run lime setup android         

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Force rebuild native libs
        run: haxelib run lime rebuild linc_luajit android -clean

      - name: Clean Android
        if: ${{ github.event.inputs.clean == 'true' }}
        run: haxelib run lime clean android
    
      - name: Build Android
        run: |
         echo "${{ github.run_id }}" > VERSION
         haxelib run lime build android -ONLY_ARMV7 -D officialBuild -D LUA_ALLOWED
         find . -name "*.apk"
      
      - uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug/PsychEngine-debug.apk
          
  buildiOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
          architecture: arm64

      - name: Setup environment
        run: |
          brew install lua
          haxelib setup ~/haxelib

      - name: Run setup script
        run: |
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Setup iOS
        run: echo "n" | haxelib run lime setup ios

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
     
      - name: Rebuild LuaJIT
        run: haxelib run lime rebuild linc_luajit ios -clean -verbose --skip-dependencies

      - name: Clean iOS
        if: ${{ github.event.inputs.clean == 'true' }}
        run: haxelib run lime clean ios

      - name: Build iOS
        run: |
          echo "${{ github.run_id }}" > VERSION
          haxelib run lime build ios -D officialBuild -D LUA_ALLOWED -nosign
           
      - name: Compile Xcode Project
        run: |
          xcodebuild \
           -project export/release/ios/PsychEngine.xcodeproj \
           -scheme PsychEngine \
           -configuration Release \
           -sdk iphoneos \
           -derivedDataPath $PWD/build \
           CODE_SIGNING_ALLOWED=NO \
           CODE_SIGNING_REQUIRED=NO \
           CODE_SIGN_IDENTITY="" \
           build

      - name: Export Ipa
        run: |
          mkdir -p Payload
          
          cp -r $PWD/build/Build/Products/Release-iphoneos/PsychEngine.app Payload/
          
          mkdir -p outputs/ipa/debug
          zip -qr outputs/ipa/debug/PsychEngine-debug.ipa Payload
          
      - name: Find IPA
        run: find . -name "*.ipa"

      - uses: actions/upload-artifact@v4
        with:
          name: iosBuild
          path: outputs/ipa/debug/PsychEngine-debug.ipa
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        with:
          name: iosApp
          path: export/ios/build/Release-iphoneos/PsychEngine.app       
